# Generated by Django 2.2.1 on 2019-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='lastname',
        ),
    ]
