# Generated by Django 2.2.1 on 2019-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190603_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
