# Generated by Django 2.2.1 on 2019-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
